### ISSUE TITLE
Add Windows builds?

### ISSUE THREAD

**Issue by jrbourbeau** [conda-forge/pyorc-feedstock#9]
Looking at the [changelog entry for the 0.4.0 release](https://pyorc.readthedocs.io/en/latest/changelog.html) is appears experimental support for added for Windows. Is there any limitation preventing `pyorc` from supporting Windows builds?

https://github.com/conda-forge/pyorc-feedstock/blob/6bda07bc8e73ca191d2df6748fc5d74ea6548b83/recipe/meta.yaml#L13

**Comment by jrbourbeau** [comment]
Gotcha, thanks for the quick reply @noirello. Mind if we keep this issue open as a reminder to enable Windows builds here once orc offers them?

**Comment by noirello** [comment]
Sure, no problem.

**Comment by jakirkham** [comment]
Probably still good to have

**Comment by noirello** [comment]
Add Windows to the build. The package has been already uploaded.
